import * as THREE from './three.module.js';
const canvas=document.querySelector('#flowers'),stage=document.querySelector('#stage');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});}catch(e){document.querySelector('#loading').textContent='Activa la aceleración gráfica de tu navegador para ver las flores en 3D.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,80);camera.position.set(0,1.4,10.7);camera.lookAt(0,.1,0);
scene.add(new THREE.HemisphereLight(0xfff6ce,0x45523b,2.6));const sun=new THREE.DirectionalLight(0xffe7a3,3.5);sun.position.set(-3,6,5);scene.add(sun);const rim=new THREE.DirectionalLight(0xffd655,2.3);rim.position.set(4,3,-3);scene.add(rim);const fill=new THREE.DirectionalLight(0xeaf5ff,.7);fill.position.set(-4,0,1);scene.add(fill);
const root=new THREE.Group();scene.add(root);let seed=31;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function material(color,roughness=.64){return new THREE.MeshStandardMaterial({color,roughness,side:THREE.DoubleSide});}
const mats={gold:material('#f9b916'),yellow:material('#ffe047'),lemon:material('#fff076'),light:material('#fff1a3'),orange:material('#e8a316'),green:material('#527e32'),darkgreen:material('#234d28'),leaf:material('#658d43'),center:material('#472c13'),seed:material('#9b6723'),paper:material('#c5b18a',.92),ribbon:material('#e5bd49',.38)};
const sphere=new THREE.SphereGeometry(1,10,7),cylinder=new THREE.CylinderGeometry(1,1,1,7),petals={};
function petalGeo(kind){if(petals[kind])return petals[kind];const vs=[],uv=[],idx=[],nx=9,ny=14;for(let j=0;j<=ny;j++){const t=j/ny;for(let i=0;i<=nx;i++){const s=i/nx*2-1;let w=Math.pow(Math.sin(Math.PI*t),kind==='rose'?.42:.72);let z=kind==='tulip'? .52*t*t + .21*s*s*Math.sin(Math.PI*t):kind==='rose'? .4*Math.sin(t*2.3)+.24*s*s*Math.sin(Math.PI*t):.13*Math.sin(t*Math.PI)-.16*t*t+.12*s*s*Math.sin(Math.PI*t);vs.push(s*w*.5,t,z);uv.push(i/nx,t);}}for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){let a=j*(nx+1)+i;idx.push(a,a+1,a+nx+1,a+1,a+nx+2,a+nx+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vs,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();petals[kind]=g;return g;}
let batches=new Map(),flowers=[];const dummy=new THREE.Object3D(),temp=new THREE.Matrix4();
function instance(geo,mat,pos,scale,rotation,parent){dummy.position.copy(pos);dummy.scale.copy(scale);dummy.rotation.set(...rotation);dummy.updateMatrix();temp.copy(dummy.matrix);if(parent)temp.premultiply(parent);let key=geo.uuid+mat.uuid;if(!batches.has(key))batches.set(key,{geo,mat,matrices:[]});batches.get(key).matrices.push(temp.clone());}
const v=(x,y,z)=>new THREE.Vector3(x,y,z);
function stem(a,b,width,mat=mats.green){let d=b.clone().sub(a);dummy.position.copy(a).add(b).multiplyScalar(.5);dummy.quaternion.setFromUnitVectors(v(0,1,0),d.clone().normalize());dummy.scale.set(width,d.length(),width);dummy.updateMatrix();const key=cylinder.uuid+mat.uuid;if(!batches.has(key))batches.set(key,{geo:cylinder,mat,matrices:[]});batches.get(key).matrices.push(dummy.matrix.clone());}
function leaf(at,angle,size=.7){const m=new THREE.Matrix4().makeRotationY(angle);m.setPosition(at);instance(petalGeo('leaf'),mats.leaf,v(0,0,0),v(size*.52,size,1),[.6,0,-.95],m);instance(petalGeo('leaf'),mats.darkgreen,v(0,0,0),v(size*.48,size*.96,1),[.6,0,1.15],m);}
function blossom(type,p,size){const g=new THREE.Object3D();g.position.copy(p);g.rotation.set(-.3+rand()*.3,(rand()-.5)*.55,(rand()-.5)*.5);g.updateMatrix();const base=g.matrix;let r;
if(type==='sunflower'||type==='daisy'){const big=type==='sunflower',radius=big?.28:.13;for(let layer=0;layer<2;layer++){let n=big?24:17;for(let i=0;i<n;i++){let a=i/n*Math.PI*2+layer*.12;r=radius*.74;instance(petalGeo('daisy'),layer?mats.yellow:mats.gold,v(-Math.sin(a)*r*size,Math.cos(a)*r*size,layer*.045*size),v((big?.22:.135)*size,(big?.59:.4)*size,size),[0,0,a],base);}}
instance(sphere,big?mats.center:mats.orange,v(0,0,.025*size),v(radius*size,radius*size,.13*size),[0,0,0],base);let n=big?190:55;for(let i=0;i<n;i++){let a=i*2.399963,r=radius*Math.sqrt(i/n)*.98;instance(sphere,i%3===0?mats.seed:(big?mats.center:mats.gold),v(Math.cos(a)*r*size,Math.sin(a)*r*size,(.055+.085*Math.sqrt(1-r*r/(radius*radius)))*size),v(.021*size,.023*size,.023*size),[0,0,a],base);}
}else if(type==='tulip'){const t=new THREE.Object3D();t.rotation.x=.85;t.updateMatrix();const bm=base.clone().multiply(t.matrix);for(let layer=0;layer<2;layer++)for(let i=0;i<3;i++){let a=i/3*Math.PI*2+layer*Math.PI/3;const q=new THREE.Object3D();q.rotation.y=a;q.updateMatrix();instance(petalGeo('tulip'),layer?mats.lemon:mats.yellow,v(0,-.18*size,.07*size),v(.65*size,.94*size,.75*size),[-.13,0,0],bm.clone().multiply(q.matrix));}
}else{for(let layer=0;layer<5;layer++){let n=layer<2?9:7;let radius=.22-layer*.043;for(let i=0;i<n;i++){let a=i/n*Math.PI*2+layer*.53;instance(petalGeo('rose'),layer%2?mats.yellow:mats.lemon,v(-Math.sin(a)*radius*size,Math.cos(a)*radius*size,layer*.072*size),v((.52-layer*.072)*size,(.52-layer*.084)*size,(1-layer*.12)*size),[.18+layer*.1,0,a],base);}}instance(sphere,mats.gold,v(0,0,.29*size),v(.09*size,.09*size,.07*size),[0,0,0],base);}}
let bouquetGroup=new THREE.Group();root.add(bouquetGroup);
function build(type){seed=31;batches=new Map();for(const child of bouquetGroup.children){if(child.isInstancedMesh)child.dispose();if(child.userData.unique)child.geometry.dispose();}root.remove(bouquetGroup);bouquetGroup=new THREE.Group();root.add(bouquetGroup);const n=type==='sunflower'?11:type==='tulip'?23:21;for(let i=0;i<n;i++){const a=i*2.399963;const radius=Math.sqrt(i/(n-1))*1.38;let p=v(Math.cos(a)*radius,1.04+Math.sqrt(Math.max(0,1-radius*radius/2.5))*.72+(rand()-.5)*.3,Math.sin(a)*radius*.68);const kind=type==='mixed'?['sunflower','rose','tulip','daisy','daisy'][i%5]:type==='rose'?(i%3?'rose':'daisy'):type;let size=kind==='sunflower'?(type==='mixed'?.83:.88):kind==='daisy'?.83:.86;stem(v((rand()-.5)*.32,-2.05,(rand()-.5)*.25),p,.018);leaf(p.clone().multiplyScalar(.44).add(v(0,-.65,0)),a,.65+rand()*.35);blossom(kind,p,size);}
for(let i=0;i<15;i++){let a=i*2.399963;const p=v(Math.cos(a)*1.65,.65+rand()*.75,Math.sin(a)*.83);stem(v(0,-1.5,0),p,.014,mats.darkgreen);leaf(p,a,.68);}
// Tiny branching sprays of golden buds around the silhouette.
for(let i=0;i<9;i++){const a=i*2.3999,tip=v(Math.cos(a)*1.75,1+rand()*.8,Math.sin(a)*.82);const origin=v(tip.x*.55,-.25,tip.z*.55);stem(origin,tip,.009);for(let j=0;j<5;j++){const b=tip.clone().add(v((rand()-.5)*.4,(rand()-.5)*.35,(rand()-.5)*.22));stem(tip.clone().lerp(origin,.25),b,.006);instance(sphere,mats.light,b,v(.043,.043,.043),[0,0,0]);}}
// An open, folded paper sleeve; every face is actual 3D geometry.
const positions=[],indices=[];const segments=72;for(let j=0;j<=1;j++)for(let i=0;i<=segments;i++){const a=i/segments*Math.PI*2,fold=Math.sin(a*12)*.035;const radius=j?1.12+fold:.25;const y=j?-.1+Math.sin(a*3+.3)*.2:-1.83;positions.push(Math.cos(a)*radius,y,Math.sin(a)*radius*.68);}for(let i=0;i<segments;i++){let a=i,b=i+segments+1;indices.push(a,a+1,b,a+1,b+1,b);}const paperGeo=new THREE.BufferGeometry();paperGeo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));paperGeo.setIndex(indices);paperGeo.computeVertexNormals();const paper=new THREE.Mesh(paperGeo,mats.paper);paper.userData.unique=true;bouquetGroup.add(paper);
const tie=new THREE.Mesh(new THREE.TorusGeometry(.3,.038,7,45),mats.ribbon);tie.rotation.x=Math.PI/2;tie.position.y=-1.65;tie.scale.y=.72;tie.userData.unique=true;bouquetGroup.add(tie);
for(const dir of [-1,1]){const curve=new THREE.CatmullRomCurve3([v(0,-1.63,.23),v(dir*.46,-1.39,.3),v(dir*.46,-1.72,.34),v(0,-1.63,.25),v(dir*.25,-2.06,.3)]);const ribbon=new THREE.Mesh(new THREE.TubeGeometry(curve,32,.03,6,false),mats.ribbon);ribbon.userData.unique=true;bouquetGroup.add(ribbon);}
for(const b of batches.values()){const mesh=new THREE.InstancedMesh(b.geo,b.mat,b.matrices.length);b.matrices.forEach((m,i)=>mesh.setMatrixAt(i,m));mesh.instanceMatrix.needsUpdate=true;bouquetGroup.add(mesh);}root.scale.setScalar(.93);}
build('mixed');
// Soft ground contact and suspended pollen add depth without covering the bouquet.
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=128;shadowCanvas.height=128;const ctx=shadowCanvas.getContext('2d'),grad=ctx.createRadialGradient(64,64,0,64,64,64);grad.addColorStop(0,'rgba(0,0,0,.38)');grad.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(6,3),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-2.22;scene.add(shadow);
const dustGeo=new THREE.BufferGeometry(),dust=new Float32Array(90*3);for(let i=0;i<dust.length;i+=3){dust[i]=(rand()-.5)*7;dust[i+1]=(rand()-.5)*6;dust[i+2]=(rand()-.5)*4-1;}dustGeo.setAttribute('position',new THREE.BufferAttribute(dust,3));const pollen=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xffde76,size:.021,transparent:true,opacity:.5,depthWrite:false}));scene.add(pollen);
let auto=!matchMedia('(prefers-reduced-motion: reduce)').matches,drag=false,lastX=0,lastY=0,targetY=-.12,targetX=.02,zoom=10.7,lastTime=0,bright=false;
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);resize();
function updateRotate(){const b=document.querySelector('#rotate');b.classList.toggle('active',auto);b.setAttribute('aria-label',auto?'Pausar giro automático':'Activar giro automático');b.title=b.getAttribute('aria-label');}updateRotate();
canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);auto=false;updateRotate();});canvas.addEventListener('pointermove',e=>{if(!drag)return;targetY+=(e.clientX-lastX)*.009;targetX=THREE.MathUtils.clamp(targetX+(e.clientY-lastY)*.004,-.4,.5);lastX=e.clientX;lastY=e.clientY;});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.006,7,14);},{passive:false});document.querySelector('#zoom-in').onclick=()=>zoom=Math.max(7,zoom-.8);document.querySelector('#zoom-out').onclick=()=>zoom=Math.min(14,zoom+.8);document.querySelector('#rotate').onclick=()=>{auto=!auto;updateRotate();};document.querySelector('#reset').onclick=()=>{targetY=-.12;targetX=.02;zoom=10.7;};document.querySelector('#light').onclick=()=>{bright=!bright;sun.intensity=bright?5:3.5;rim.intensity=bright?1.4:2.3;renderer.toneMappingExposure=bright?1.65:1.35;document.querySelector('#light').classList.toggle('active',bright);};
document.querySelectorAll('.bouquet').forEach((button,index)=>button.onclick=()=>{build(button.dataset.type);document.querySelectorAll('.bouquet').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelector('#scene-number').textContent=`0${index+1} / 04`;document.querySelector('#scene-name').textContent=button.querySelector('strong').textContent.toUpperCase();document.querySelector('#announcement').textContent=`Mostrando ${button.querySelector('strong').textContent}`;targetY=-.12;targetX=.02;});
let visible=true;document.addEventListener('visibilitychange',()=>{visible=!document.hidden;lastTime=0;});function animate(t){requestAnimationFrame(animate);if(!visible)return;const dt=lastTime?Math.min((t-lastTime)/1000,.05):0;lastTime=t;if(auto)targetY+=dt*.085;root.rotation.y+=(targetY-root.rotation.y)*.08;root.rotation.x+=(targetX-root.rotation.x)*.08;if(!matchMedia('(prefers-reduced-motion: reduce)').matches){root.position.y=Math.sin(t*.0008)*.025;pollen.rotation.y=t*.000025;}camera.position.z+=(zoom-camera.position.z)*.08;camera.lookAt(0,.15,0);renderer.render(scene,camera);}requestAnimationFrame(animate);document.querySelector('#loading').remove();
